### ISSUE TITLE
Allow arguments to be passed through the control wrapper functions

### ISSUE THREAD

**Issue by StuieT85** [tidymodels/stacks#102]
Is it possible to allow additional options that are given to the wrapper functions to be passed through to tune's control functions. For instance allowing the use of the verbose tags. I know you could use tune's functions ensuring that save_pred and save_workflow were set to TRUE but I think it would be more convenient.

I initially created this

```r
control_stack_grid2 <- function(...) {
  options <- rlang::list2(...)
  
  options$save_pred <-  TRUE
  options$save_workflow <-  TRUE
  
  do.call(tune::control_grid, options)
}
```

It seems to do what I wanted it to do. It just lists the options, sets the appropriate options to TRUE and then passes it on to the appropriate tune function.

**Comment by simonpcouch** [comment]
Thanks for the issue!

This is pretty slick! I like the idea, though I do think I would recommend that folks use `tune`'s control functions when setting options beyond those that `stacks`' functions take care of. `stacks`' control functions are meant to be a quick and easy shorthand for setting options that aren't super essential to understanding how the package is fitting ensemble models, and I think `tune`'s control functions + docs otherwise do a great job of reducing + explaining that complexity.
