### ISSUE TITLE
Trouble with collating predictions

### ISSUE THREAD

**Issue by markushaun** [tidymodels/stacks#56]
I'm having trouble with collating the out-of-sample predictions...

```r
predictions <- stacks::stacks() %>%
        add_candidates(tune_ridge_fit) %>%
        add_candidates(tune_lasso_fit) %>%
        add_candidates(tune_elastic_fit) %>%
        add_candidates(tune_rf_fit) %>%
        add_candidates(tune_xgboost_fit)
predictions
```

...is followed by the error message: "Error: The inputted `candidates` argument was not generated with the appropriate control settings. Please see ?control_stack." Unfortunately, ?control_stack says that there is no documentation.

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

**Comment by simonpcouch** [comment]
Hmm, strange. What do you mean by "says there is no documentation"?

If running `?control_stack` isn't pulling up the relevant documentation for you for whatever reason, the name of one of the functions sharing that help-file is `control_stack_grid()`. Here's the version of that help-file hosted on the package website: https://stacks.tidymodels.org/reference/control_stack.html

**Comment by topepo** [comment]
Can you please provide a **minimal** reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.
