### ISSUE TITLE
fit_members() should look for dependencies

### ISSUE THREAD

**Issue by topepo** [tidymodels/stacks#70]
If you do not create the initial candidate models in the same session as the one where `fit_members()` is executed, the `parsnip` adjacent packages are not loaded (and an error occurs). Inside of `fit_members()`, we might want to run `required_packages()` and load them before fitting.

**Comment by simonpcouch** [comment]
Ah, right. Thanks for catching this. Thinking about CRAN restrictions, I would think our best strategy here is to

* Load the package silently if installed (assuming this is fair game?)
* Error informatively if the packages aren't installed

This probably ought to be the case at the `predict` step as well. Will give a go at this here soon unless I hear otherwise.

**Comment by topepo** [comment]
`parsnip` and `recipes` will load the packages. I would find the list of requirements via `required_packages()` then check them with `rlang::is_installed()` (which will throw an error when needed).
