### ISSUE TITLE
bootstrap times parameter 

### ISSUE THREAD

**Issue by SewerynGrodny** [tidymodels/stacks#94]
Hi,
it would be useful to add to blend_predictions function a times parameter, when it use bootstraps.
I not necessary need to boostraps it 25 time. Sometimes I just need to get initial results.

https://github.com/tidymodels/stacks/blob/0985737a90c3f51d6a82a503ad1fe85c5a18884d/R/blend_predictions.R#L194

Thanks, for stacks packages, it's great.

Seweryn

**Comment by mattwarkentin** [comment]
I would also endorse being able to control the number of `bootstraps()` for `blend_predictions()`. Either  via `...`, `times`, or perhaps a new `control_blend()` which maybe could supplant the default of `control_grid()` since `control_grid()` has arguments that `blend_predictions()` has to protect against (i.e. `extract`).
